### ISSUE TITLE
Two spelling errors in this sentence

### ISSUE THREAD

**Issue by ValerieHMoore** [learn-co-curriculum/js-basics-functions-lab#15]
Need to take the apostrophe out of "it's" in this sentence:
 "They would like you to write a function that takes in a pickup location for a passenger, and returns the number of blocks from it's headquarters on 42nd street."

Also, 42nd street should be 42nd Street.

Thank you.

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
