### ISSUE TITLE
Elaborate on test's description

### ISSUE THREAD

**Issue by BebopVinh** [learn-co-curriculum/js-basics-functions-lab#16]
Would help if the test or README would explain that the number argument being passed into the function represent the street number. And each street is one block away from the previous/next. 

`distanceTravelledInFeet` is misspelled. Has an extra "L" in "Traveled".

**Comment by lizbur10** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

Thanks for contributing! 💙
