### ISSUE TITLE
before all hook error

### ISSUE THREAD

**Issue by CodeJonesW** [learn-co-curriculum/js-basics-functions-lab#17]
learn seems to not be able to run my tests due to it looking for async code but I do not believe i have async code in my test file. It is hard for me to talk on the issue since my knowledge of what seems to be happening behind the scenes is limited. I have had this on multiple labs since beginning module 3 this weekend. We were able to get my tests to work by running npm install and  implementing this code in the body of the html file. Would really appreciate any help resolving to avoid future errors.

<script src ="node_modules/mocha/mocha.js"></script>
  <script src = "node_modules/chai/chai.js"></script>
  <div id ="mocha"></div>

  <script class='mocha-init'>
    mocha.setup('bdd');
  </script>
  <script src="index.js"></script>
  <script src="./test/indexTest.js"></script>
  <script class="mocah-exec">
    mocha.run()
  </script>

**Comment by lizbur10** [comment]
Thank you for spotting this issue and providing feedback.

The materials have been updated to address this issue so I am going to close it.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

Thanks for contributing to the Flatiron curriculum. 💙
