### ISSUE TITLE
test file

### ISSUE THREAD

**Issue by sdklos** [learn-co-curriculum/js-basics-functions-lab#4]
`describe('distanceFromHqInBlocks()', function () {
    it('returns a distance in feet', function () {
      expect(distanceFromHqInBlocks(43)).to.equal(1);
    });`

should say 'returns distance from headquarters'

**Comment by gj** [comment]
Fixed (close enough) in https://github.com/learn-co-curriculum/js-basics-functions-lab/commit/80a1a242f144b4705251fcf200a6eb41e3df04cc. Students know it's the distance from the HQ based on the function's name. 🙂 Thanks @sdklos !
