### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by SuperConfuserUser** [learn-co-curriculum/js-basics-functions-lab#6]
Some typos that seem to be from legacy version of this lesson.

Introduction>3rd Paragraph 
- "Write a function called calculateVertical that takes in the beginning and destination blocks and returns the number of feet travelled." Current lesson has no mention of calculateVertical in the test. Assuming this should be updated to distanceTravelledInFeet.
- "Each block in Manhattan is 264 feet long. For example calculateVertical(34, 38) returns 1056 ((38-34)*4)" Equation says to multiply by 4, but it should be 264 of course. (38-34)*264

Instructions>bullet 2 distanceFromHqInFeet
- "Returns the number of blocks from Scuber's headquarters to the pickup location." Should be returns the number of feet instead of blocks?

Instructions>bullet 4 calculatesFarePrice
"The first four hundred feet are free. For a distance between 400 and 2000 feet, the price is 2 cents per foot." Might want to clarify that distances under 400 are free or update the test. Right now, it charges  total distance*0.02/ft. If FIRST 400 ft are free, it should be (total distance - 400) * 0.02/ft.

**Comment by adilasif** [comment]
I think I caught everything in that PR... Paging @aviflombaum (sorry!)

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @unenlightened and @adilasif.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
